### PR TITLE
Create a server factory function

### PR DESCRIPTION
**Pull request by miguel5g**
Creating a factory function will help in future tests, leaving all route configuration logic independent.

### CODE REVIEW

**Comment by BrenoHaraujo2503** [comment]
taking advantage of the pr would not be it be better to separate the routes file?

**Comment by miguel5g** [comment]
> taking advantage of the pr would not be it be better to separate the routes file?

Yes, I didn't do that because I didn't want to add code beyond what I already had, just a refactoring, but if you want I can implement it.

**Comment by BrenoHaraujo2503** [comment]
> > taking advantage of the pr would not be it be better to separate the routes file?
> 
> Yes, I didn't do that because I didn't want to add code beyond what I already had, just a refactoring, but if you want I can implement it.

The implementation would be a good one to facilitate future pr's.

**Review by BrenoHaraujo2503 — APPROVED** [review]
Good Job!

**Pull request merged**
